name: Sample CICD Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    name: Build, Test, and Deploy to IIS
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.100'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o .\publish

      - name: Deploy to IIS
        uses: ChristopheLav/iis-deploy@v1
        with:
          website-name: '"Default Web Site/Portal_CICD"'
          msdeploy-service-url: 'https://20.205.99.114:8172/msdeploy.axd'
          msdeploy-username: '${{ secrets.AZURE_VM_USERNAME }}'
          msdeploy-password: '${{ secrets.AZURE_VM_PASSWORD }}'
          source-path: '.\publish'
          skip-extra-files: false
